# Generated by Django 5.1.15 on 2026-06-03 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('capital', models.CharField(max_length=100, verbose_name='Chef-lieu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Préfecture',
                'verbose_name_plural': 'Préfectures',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('capital', models.CharField(max_length=100, verbose_name='Chef-lieu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PerteDocsTG', max_length=100, verbose_name='Nom du site')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Accroche')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone contact')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Message maintenance')),
                ('allow_registrations', models.BooleanField(default=True, verbose_name='Inscriptions ouvertes')),
                ('max_declarations_per_user', models.PositiveIntegerField(default=10, verbose_name='Max déclarations par utilisateur')),
                ('receipt_validity_days', models.PositiveIntegerField(default=90, verbose_name='Validité récépissé (jours)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='core.prefecture')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['prefecture__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='core.region'),
        ),
        migrations.AlterUniqueTogether(
            name='prefecture',
            unique_together={('region', 'name')},
        ),
    ]
