# Generated by Django 5.1.15 on 2026-06-03 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='document', max_length=50, verbose_name='Icône')),
                ('requires_number', models.BooleanField(default=True, verbose_name='Nécessite un numéro')),
                ('processing_days', models.PositiveSmallIntegerField(default=3, verbose_name='Délai traitement (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True, verbose_name='Numéro de déclaration')),
                ('verification_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Token de vérification')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_progress', 'En cours'), ('under_review', 'En vérification'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('archived', 'Archivé'), ('complement_requested', 'Complément demandé')], db_index=True, default='draft', max_length=30, verbose_name='Statut')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nationality', models.CharField(default='Togolaise', max_length=100, verbose_name='Nationalité')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro du document')),
                ('document_issue_date', models.DateField(blank=True, null=True, verbose_name='Date de délivrance')),
                ('document_issue_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de délivrance')),
                ('document_authority', models.CharField(blank=True, max_length=200, verbose_name='Autorité émettrice')),
                ('loss_date', models.DateField(verbose_name='Date estimée de perte')),
                ('loss_place', models.CharField(max_length=300, verbose_name='Lieu de perte')),
                ('loss_circumstances', models.TextField(verbose_name='Circonstances de perte')),
                ('loss_description', models.TextField(verbose_name='Description détaillée')),
                ('honor_declaration', models.BooleanField(default=False, verbose_name="Déclaration sur l'honneur")),
                ('electronic_signature', models.TextField(blank=True, verbose_name='Signature électronique')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('agent_notes', models.TextField(blank=True, verbose_name="Notes de l'agent")),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('complement_requested', models.TextField(blank=True, verbose_name='Complément demandé')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Traitement débuté le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('receipt_generated', models.BooleanField(default=False, verbose_name='Récépissé généré')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Fichier récépissé')),
                ('receipt_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Récépissé généré le')),
                ('receipt_expires_at', models.DateField(blank=True, null=True, verbose_name='Expiration récépissé')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné')),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to=settings.AUTH_USER_MODEL, verbose_name='Déclarant')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='core.prefecture', verbose_name='Préfecture')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='declarations.documenttype', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Déclaration',
                'verbose_name_plural': 'Déclarations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=30, verbose_name='Ancien statut')),
                ('new_status', models.CharField(max_length=30, verbose_name='Nouveau statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='declarations.declaration')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statuts',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['declaration_number'], name='declaration_declara_c4baf5_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['status'], name='declaration_status_e13135_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['declarant', 'status'], name='declaration_declara_5baf75_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['created_at'], name='declaration_created_d5bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['verification_token'], name='declaration_verific_327dd0_idx'),
        ),
    ]
