# Generated by Django 5.1.15 on 2026-06-04 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='declarations.documenttype', verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='loss_circumstances',
            field=models.TextField(blank=True, verbose_name='Circonstances de perte'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='loss_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date estimée de perte'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='loss_description',
            field=models.TextField(blank=True, verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='loss_place',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lieu de perte'),
        ),
    ]
