# Generated by Django 5.2.15 on 2026-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0003_documentfound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfound',
            name='found_by',
            field=models.CharField(blank=True, help_text='Nom de la personne ou institution ayant trouvé le document', max_length=200, verbose_name='Trouvé par'),
        ),
    ]
