# Generated by Django 5.1.15 on 2026-06-03 19:52

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Téléphone')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Genre')),
                ('nationality', models.CharField(default='Togolaise', max_length=100, verbose_name='Nationalité')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('role', models.CharField(choices=[('citizen', 'Citoyen'), ('agent', 'Agent Administratif'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur')], default='citizen', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Téléphone vérifié')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Mode sombre')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='Notifications SMS')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives échouées')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name="Verrouillé jusqu'au")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.prefecture', verbose_name='Préfecture')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True, verbose_name='ID Agent')),
                ('agent_type', models.CharField(choices=[('prefectural', 'Agent Préfectoral'), ('regional', 'Agent Régional'), ('national', 'Agent National')], max_length=20, verbose_name="Type d'agent")),
                ('department', models.CharField(max_length=200, verbose_name='Département')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core.prefecture', verbose_name='Préfecture')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core.region', verbose_name='Région')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Agent',
                'verbose_name_plural': 'Profils Agents',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
    ]
