# Generated by Django 5.1.15 on 2026-06-03 20:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declarations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('identity', "Pièce d'identité"), ('proof_address', 'Justificatif de domicile'), ('proof_loss', 'Justificatif de perte'), ('photo', 'Photo'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type')),
                ('file', models.FileField(upload_to=documents.models.declaration_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nom original')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum SHA256')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valide')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Notes de validation')),
                ('is_virus_scanned', models.BooleanField(default=False, verbose_name='Antivirus passé')),
                ('virus_scan_result', models.CharField(blank=True, max_length=50, verbose_name='Résultat scan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploadé le')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='declarations.declaration', verbose_name='Déclaration')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro récépissé')),
                ('file', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Fichier PDF')),
                ('qr_code_data', models.TextField(blank=True, verbose_name='Données QR Code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Image QR Code')),
                ('digital_signature', models.TextField(blank=True, verbose_name='Signature numérique')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Émis le')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expire le')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Téléchargements')),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='declarations.declaration', verbose_name='Déclaration')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Récépissé',
                'verbose_name_plural': 'Récépissés',
                'ordering': ['-issued_at'],
            },
        ),
    ]
