# Generated by Django 5.1.15 on 2026-06-03 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Échec connexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('download', 'Téléchargement'), ('submit', 'Soumission'), ('validate', 'Validation'), ('reject', 'Rejet'), ('export', 'Export'), ('import', 'Import'), ('permission_change', 'Changement de permission'), ('config_change', 'Changement de configuration'), ('password_change', 'Changement de mot de passe'), ('two_factor', 'Authentification 2FA')], db_index=True, max_length=30, verbose_name='Action')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name="Type d'objet")),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Représentation')),
                ('changes', models.JSONField(default=dict, verbose_name='Changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, verbose_name='Referer')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='audit_audit_user_id_ac289d_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['ip_address'], name='audit_audit_ip_addr_685e3f_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_997ff9_idx')],
            },
        ),
    ]
