# Generated by Django 5.2.15 on 2026-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('declaration_submitted', 'Déclaration soumise'), ('declaration_validated', 'Déclaration validée'), ('declaration_rejected', 'Déclaration rejetée'), ('complement_requested', 'Complément demandé'), ('receipt_ready', 'Récépissé disponible'), ('document_found', 'Document retrouvé'), ('system', 'Système'), ('info', 'Information'), ('warning', 'Avertissement')], max_length=40, verbose_name='Type'),
        ),
    ]
